title: "Computational Techniques: Python Basics"
author: Krishna Patel
logo: ""

execute:
  execute_notebooks: "off"

html:
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar: false
  extra_path:
    - _static

repository:
  url: https://github.com/crisnapatel/python-basics
  branch: main

# Enable JupyterLite for interactive code
sphinx:
  extra_extensions:
    - jupyterlite_sphinx
  config:
    jupyterlite_contents: ["notebooks/"]
    jupyterlite_dir: "lite"
